### PR TITLE
Azerbaijani strings have been updated.

### PR DESCRIPTION
**Pull request by shahinf27**
In this translation string, the latest translations have been added and many translations have been updated.

### CODE REVIEW

**Comment by ingbrzy** [comment]
this repo does not accept PR

**Comment by shahinf27** [comment]
So how can I contribute to this repo?

**Comment by ingbrzy** [comment]
this repo is just to help translators to get AOSP strings for A14 ROMs.. it is not used as translations source for our ROMs..

**Comment by shahinf27** [comment]
> this repo is just to help translators to get AOSP strings for A14 ROMs.. it is not used as translations source for our ROMs..

Thanks for the detailed information. I added a repository with Azerbaijani translations for HyperOS. Can you please check? I want to know if there are any more files to add.

**Comment by ingbrzy** [comment]
compare to this repo
https://github.com/ingbrzy/Xiaomi.eu-HyperOS-1.0-XML-Compare/tree/master/shennong

**Pull request closed without merging**
